//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem/Player_Input_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_Input_Actions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_Input_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player_Input_Actions"",
    ""maps"": [
        {
            ""name"": ""Main_UI"",
            ""id"": ""65bf522d-90ca-4fc9-a8f4-7fa95e7b8ca1"",
            ""actions"": [
                {
                    ""name"": ""First_Touch"",
                    ""type"": ""Button"",
                    ""id"": ""522187f9-c009-4405-9b40-b71996d400d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""fd54cb6b-9a9c-4ebe-bf4f-71494e9afe5a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aebe74c3-267a-415f-9de7-08f89d3da0db"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""First_Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd0a0f8b-5696-4fd6-b478-ef7cecf22cff"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""First_Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d47575e1-db6b-4f70-a0e3-12ed1161dd84"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9337b655-2701-4c07-92f7-a513c99be7be"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Main_UI
        m_Main_UI = asset.FindActionMap("Main_UI", throwIfNotFound: true);
        m_Main_UI_First_Touch = m_Main_UI.FindAction("First_Touch", throwIfNotFound: true);
        m_Main_UI_Back = m_Main_UI.FindAction("Back", throwIfNotFound: true);
    }

    ~@Player_Input_Actions()
    {
        UnityEngine.Debug.Assert(!m_Main_UI.enabled, "This will cause a leak and performance issues, Player_Input_Actions.Main_UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main_UI
    private readonly InputActionMap m_Main_UI;
    private List<IMain_UIActions> m_Main_UIActionsCallbackInterfaces = new List<IMain_UIActions>();
    private readonly InputAction m_Main_UI_First_Touch;
    private readonly InputAction m_Main_UI_Back;
    public struct Main_UIActions
    {
        private @Player_Input_Actions m_Wrapper;
        public Main_UIActions(@Player_Input_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @First_Touch => m_Wrapper.m_Main_UI_First_Touch;
        public InputAction @Back => m_Wrapper.m_Main_UI_Back;
        public InputActionMap Get() { return m_Wrapper.m_Main_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Main_UIActions set) { return set.Get(); }
        public void AddCallbacks(IMain_UIActions instance)
        {
            if (instance == null || m_Wrapper.m_Main_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Main_UIActionsCallbackInterfaces.Add(instance);
            @First_Touch.started += instance.OnFirst_Touch;
            @First_Touch.performed += instance.OnFirst_Touch;
            @First_Touch.canceled += instance.OnFirst_Touch;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
        }

        private void UnregisterCallbacks(IMain_UIActions instance)
        {
            @First_Touch.started -= instance.OnFirst_Touch;
            @First_Touch.performed -= instance.OnFirst_Touch;
            @First_Touch.canceled -= instance.OnFirst_Touch;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
        }

        public void RemoveCallbacks(IMain_UIActions instance)
        {
            if (m_Wrapper.m_Main_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMain_UIActions instance)
        {
            foreach (var item in m_Wrapper.m_Main_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Main_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Main_UIActions @Main_UI => new Main_UIActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IMain_UIActions
    {
        void OnFirst_Touch(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
}
