//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem/Player_Input_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_Input_Actions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_Input_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player_Input_Actions"",
    ""maps"": [
        {
            ""name"": ""Main_UI"",
            ""id"": ""65bf522d-90ca-4fc9-a8f4-7fa95e7b8ca1"",
            ""actions"": [
                {
                    ""name"": ""First_Touch"",
                    ""type"": ""Button"",
                    ""id"": ""522187f9-c009-4405-9b40-b71996d400d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""fd54cb6b-9a9c-4ebe-bf4f-71494e9afe5a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwipeBack"",
                    ""type"": ""Value"",
                    ""id"": ""6a2aacda-2493-4574-b4fc-6137dcad7718"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""56641b6d-7ffd-4f0b-b9e7-57151412129d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aebe74c3-267a-415f-9de7-08f89d3da0db"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""First_Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd0a0f8b-5696-4fd6-b478-ef7cecf22cff"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""First_Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b03f631a-8a18-4a57-8f8e-0a3771f3a79e"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Touch"",
                    ""action"": ""First_Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d47575e1-db6b-4f70-a0e3-12ed1161dd84"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9337b655-2701-4c07-92f7-a513c99be7be"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02141199-c672-4c7d-9505-b94f455a4e31"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Touch"",
                    ""action"": ""SwipeBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fb751fd-e70a-494b-bdc4-3181bad83072"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Touch"",
                    ""action"": ""SwipeBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c1c29389-ed8c-49ff-a2dd-d6eacc344feb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f0bf0882-9105-4fd8-b02e-eeed4b4b44c7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""388d2594-8be0-43a5-9c46-37a56f8f2417"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7083e78b-9068-4c5b-9dda-95c411e80e76"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a240131d-b953-4b07-ba51-39c85befa06f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""268546a5-90a6-46ad-8c98-99f08ff3b453"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Main_UI
        m_Main_UI = asset.FindActionMap("Main_UI", throwIfNotFound: true);
        m_Main_UI_First_Touch = m_Main_UI.FindAction("First_Touch", throwIfNotFound: true);
        m_Main_UI_Back = m_Main_UI.FindAction("Back", throwIfNotFound: true);
        m_Main_UI_SwipeBack = m_Main_UI.FindAction("SwipeBack", throwIfNotFound: true);
        m_Main_UI_Move = m_Main_UI.FindAction("Move", throwIfNotFound: true);
    }

    ~@Player_Input_Actions()
    {
        UnityEngine.Debug.Assert(!m_Main_UI.enabled, "This will cause a leak and performance issues, Player_Input_Actions.Main_UI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main_UI
    private readonly InputActionMap m_Main_UI;
    private List<IMain_UIActions> m_Main_UIActionsCallbackInterfaces = new List<IMain_UIActions>();
    private readonly InputAction m_Main_UI_First_Touch;
    private readonly InputAction m_Main_UI_Back;
    private readonly InputAction m_Main_UI_SwipeBack;
    private readonly InputAction m_Main_UI_Move;
    public struct Main_UIActions
    {
        private @Player_Input_Actions m_Wrapper;
        public Main_UIActions(@Player_Input_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @First_Touch => m_Wrapper.m_Main_UI_First_Touch;
        public InputAction @Back => m_Wrapper.m_Main_UI_Back;
        public InputAction @SwipeBack => m_Wrapper.m_Main_UI_SwipeBack;
        public InputAction @Move => m_Wrapper.m_Main_UI_Move;
        public InputActionMap Get() { return m_Wrapper.m_Main_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Main_UIActions set) { return set.Get(); }
        public void AddCallbacks(IMain_UIActions instance)
        {
            if (instance == null || m_Wrapper.m_Main_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Main_UIActionsCallbackInterfaces.Add(instance);
            @First_Touch.started += instance.OnFirst_Touch;
            @First_Touch.performed += instance.OnFirst_Touch;
            @First_Touch.canceled += instance.OnFirst_Touch;
            @Back.started += instance.OnBack;
            @Back.performed += instance.OnBack;
            @Back.canceled += instance.OnBack;
            @SwipeBack.started += instance.OnSwipeBack;
            @SwipeBack.performed += instance.OnSwipeBack;
            @SwipeBack.canceled += instance.OnSwipeBack;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IMain_UIActions instance)
        {
            @First_Touch.started -= instance.OnFirst_Touch;
            @First_Touch.performed -= instance.OnFirst_Touch;
            @First_Touch.canceled -= instance.OnFirst_Touch;
            @Back.started -= instance.OnBack;
            @Back.performed -= instance.OnBack;
            @Back.canceled -= instance.OnBack;
            @SwipeBack.started -= instance.OnSwipeBack;
            @SwipeBack.performed -= instance.OnSwipeBack;
            @SwipeBack.canceled -= instance.OnSwipeBack;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IMain_UIActions instance)
        {
            if (m_Wrapper.m_Main_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMain_UIActions instance)
        {
            foreach (var item in m_Wrapper.m_Main_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Main_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Main_UIActions @Main_UI => new Main_UIActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    public interface IMain_UIActions
    {
        void OnFirst_Touch(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnSwipeBack(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
